version: '3.3'
services:
  miniroutix:
    container_name: miniroutix
    build:
      context: ./src/
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src/:/app/:rw
